### PR TITLE
Move settings to Foreman's settings system

### PR DESCRIPTION
**Pull request by domcleal**
This uses a little-known directory that was added in 1.1 I think, which gets merged into Foreman's SETTINGS hash.  We use it in a couple of other plugins like foreman_column_view and foreman_memcache.

### CODE REVIEW

**Comment by domcleal** [comment]
ping @isratrade :)

**Comment by isratrade** [comment]
@domcleal, I don't have a 'Merge' button.  Do I have merge rights?

**Comment by domcleal** [comment]
@isratrade sorry, try now :)

**Comment by isratrade** [comment]
merged. thanks @domcleal

**Pull request merged**
